#Create ubuntu as base image
FROM ubuntu

#Install packages
RUN apt-get -y update
RUN apt update
RUN apt install software-properties-common apt-transport-https wget
RUN wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
RUN apt update
RUN apt install code
RUN apt install snapd
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get -y install python3.7
RUN snap install flutter --classic
RUN apt-get install git
RUN snap install postman
RUN python -m pip install Django
RUN pip install Flask
